# Generated by Django 2.1.5 on 2019-02-11 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_as_app', '0001_initial'),
    ]

    # remove karena di model tadinya belum ada eh salah malah edit file migration
    operations = [
        migrations.RemoveField(
            model_name='mentee',
            name='nick_name',
        ),
    ]
