# Generated by Django 2.1.5 on 2019-02-11 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_as_app', '0004_auto_20190211_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentee',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
