# Generated by Django 2.1.5 on 2019-02-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rumah_Sakit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokter',
            name='jadwal_praktek',
            field=models.CharField(max_length=255),
        ),
    ]
