# Generated by Django 2.1.5 on 2019-02-11 09:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Rumah_Sakit', '0002_auto_20190211_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokter',
            name='jadwal_praktek',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
